# Generated by Django 5.1.2 on 2025-06-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table1',
            new_name='Table',
        ),
    ]
