# Generated by Django 5.1.2 on 2025-06-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_remove_booking_status_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer',
            new_name='user',
        ),
    ]
